import { colorValues } from "./tailwindColors";
type TailwindClassValue = string[] | "number";

interface TailwindClassDefinition {
  values: TailwindClassValue;
  group: string;
  title: string;
  className: string;
  prefix: string;
  priority: number;
  useKeyAsClass?: boolean;
}

type TailwindClasses = {
  [key: string]: TailwindClassDefinition;
};

export const tailwindClasses: TailwindClasses = {
  w: {
    values: "number",
    group: "Layout",
    title: "Width",
    className: "w",
    prefix: "w-",
    priority: 0,
  },
  h: {
    values: "number",
    group: "Layout",
    title: "Height",
    className: "h",
    prefix: "h-",
    priority: 0,
  },
  maxW: {
    values: "number",
    group: "Layout",
    title: "Max Width",
    className: "max-w",
    prefix: "max-w-",
    priority: 0,
  },
  maxH: {
    values: "number",
    group: "Layout",
    title: "Max Height",
    className: "max-h",
    prefix: "max-h-",
    priority: 0,
  },
  display: {
    values: [
      "block",
      "inline-block",
      "inline",
      "flex",
      "inline-flex",
      "grid",
      "inline-grid",
      "contents",
      "list-item",
      "hidden",
    ],
    group: "Layout",
    title: "Display",
    className: "display",
    prefix: "",
    useKeyAsClass: true,
    priority: 0,
  },
  position: {
    values: ["static", "fixed", "absolute", "relative", "sticky"],
    group: "Layout",
    title: "Position",
    className: "position",
    prefix: "",
    useKeyAsClass: true,
    priority: 0,
  },
  inset: {
    values: "number",
    group: "Layout",
    title: "Inset",
    className: "inset",
    prefix: "inset-",
    priority: 0,
  },
  z: {
    values: "number",
    group: "Layout",
    title: "Z-Index",
    className: "z",
    prefix: "z-",
    priority: 0,
  },
  overflow: {
    values: ["auto", "hidden", "visible", "scroll"],
    group: "Layout",
    title: "Overflow",
    className: "overflow",
    prefix: "overflow-",
    priority: 0,
  },
  textCOLOR: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Typography",
    title: "Text Color",
    className: "text",
    prefix: "text-",
    priority: 0,
  },
  textALIGN: {
    values: ["left", "center", "right", "justify", "start", "end"],
    group: "Typography",
    title: "Text Align",
    className: "text",
    prefix: "text-",
    priority: 0,
  },
  textSIZE: {
    values: [
      "xs",
      "sm",
      "base",
      "lg",
      "xl",
      "2xl",
      "3xl",
      "4xl",
      "5xl",
      "6xl",
      "7xl",
      "8xl",
      "9xl",
    ],
    group: "Typography",
    title: "Text Size",
    className: "text",
    prefix: "text-",
    priority: 0,
  },
  fontFACE: {
    values: ["sans", "serif", "mono"],
    group: "Typography",
    title: "Font Family",
    className: "font",
    prefix: "font-",
    priority: 0,
  },
  fontSTYLE: {
    values: ["italic", "not-italic"],
    group: "Typography",
    title: "Font Style",
    className: "font",
    prefix: "",
    useKeyAsClass: true,
    priority: 0,
  },
  fontWEIGHT: {
    values: [
      "thin",
      "extralight",
      "light",
      "normal",
      "medium",
      "semibold",
      "bold",
      "extrabold",
      "black",
    ],
    group: "Typography",
    title: "Font Weight",
    className: "font",
    prefix: "font-",
    priority: 0,
  },
  m: {
    values: "number",
    group: "Spacing",
    title: "Margin",
    className: "m",
    prefix: "m-",
    priority: 1,
  },
  mx: {
    values: "number",
    group: "Spacing",
    title: "Margin X",
    className: "mx",
    prefix: "mx-",
    priority: 1,
  },
  my: {
    values: "number",
    group: "Spacing",
    title: "Margin Y",
    className: "my",
    prefix: "my-",
    priority: 1,
  },
  mt: {
    values: "number",
    group: "Spacing",
    title: "Margin Top",
    className: "mt",
    prefix: "mt-",
    priority: 1,
  },
  mr: {
    values: "number",
    group: "Spacing",
    title: "Margin Right",
    className: "mr",
    prefix: "mr-",
    priority: 1,
  },
  mb: {
    values: "number",
    group: "Spacing",
    title: "Margin Bottom",
    className: "mb",
    prefix: "mb-",
    priority: 1,
  },
  ml: {
    values: "number",
    group: "Spacing",
    title: "Margin Left",
    className: "ml",
    prefix: "ml-",
    priority: 1,
  },
  p: {
    values: "number",
    group: "Spacing",
    title: "Padding",
    className: "p",
    prefix: "p-",
    priority: 1,
  },
  px: {
    values: "number",
    group: "Spacing",
    title: "Padding X",
    className: "px",
    prefix: "px-",
    priority: 1,
  },
  py: {
    values: "number",
    group: "Spacing",
    title: "Padding Y",
    className: "py",
    prefix: "py-",
    priority: 1,
  },
  pt: {
    values: "number",
    group: "Spacing",
    title: "Padding Top",
    className: "pt",
    prefix: "pt-",
    priority: 1,
  },
  pr: {
    values: "number",
    group: "Spacing",
    title: "Padding Right",
    className: "pr",
    prefix: "pr-",
    priority: 1,
  },
  pb: {
    values: "number",
    group: "Spacing",
    title: "Padding Bottom",
    className: "pb",
    prefix: "pb-",
    priority: 1,
  },
  pl: {
    values: "number",
    group: "Spacing",
    title: "Padding Left",
    className: "pl",
    prefix: "pl-",
    priority: 1,
  },
  flex: {
    values: ["1", "auto", "initial", "none"],
    group: "Flexbox",
    title: "Flex",
    className: "flex",
    prefix: "flex-",
    priority: 1,
  },
  flexDIRECTION: {
    values: ["row", "row-reverse", "col", "col-reverse"],
    group: "Flexbox",
    title: "Flex Direction",
    className: "flex",
    prefix: "flex-",
    priority: 1,
  },
  flexWRAP: {
    values: ["wrap", "wrap-reverse", "nowrap"],
    group: "Flexbox",
    title: "Flex Wrap",
    className: "flex",
    prefix: "flex-",
    priority: 1,
  },
  justifyCONTENT: {
    values: ["start", "end", "center", "between", "around", "evenly"],
    group: "Flexbox",
    title: "Justify Content",
    className: "justify",
    prefix: "justify-",
    priority: 1,
  },
  alignITEMS: {
    values: ["start", "end", "center", "baseline", "stretch"],
    group: "Flexbox",
    title: "Align Items",
    className: "items",
    prefix: "items-",
    priority: 1,
  },
  gap: {
    values: "number",
    group: "Flexbox",
    title: "Gap",
    className: "gap",
    prefix: "gap-",
    priority: 1,
  },
  border: {
    values: ["true"],
    group: "Borders",
    title: "Border",
    className: "border",
    prefix: "",
    useKeyAsClass: true,
    priority: 2,
  },
  borderSTYLE: {
    values: ["solid", "dashed", "dotted", "double", "hidden", "none"],
    group: "Borders",
    title: "Border Style",
    className: "border",
    prefix: "border-",
    priority: 2,
  },
  borderWIDTH: {
    values: "number",
    group: "Borders",
    title: "Border Width",
    className: "border",
    prefix: "border-",
    priority: 2,
  },
  borderCOLOR: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Borders",
    title: "Border Color",
    className: "border",
    prefix: "border-",
    priority: 2,
  },
  borderSTROKE: {
    values: ["0", "2", "4", "8"],
    group: "Borders",
    title: "Border Stroke Size",
    className: "border",
    prefix: "border-",
    priority: 2,
  },
  rounded: {
    values: ["none", "sm", "md", "lg", "xl", "2xl", "3xl", "full"],
    group: "Borders",
    title: "Border Radius",
    className: "rounded",
    prefix: "rounded-",
    priority: 2,
  },
  divideWIDTH: {
    values: "number",
    group: "Borders",
    title: "Divide Width",
    className: "divide",
    prefix: "divide-",
    priority: 2,
  },
  divideCOLOR: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Borders",
    title: "Divide Color",
    className: "divide",
    prefix: "divide-",
    priority: 2,
  },
  divideSTYLE: {
    values: ["solid", "dashed", "dotted", "double", "none"],
    group: "Borders",
    title: "Divide Style",
    className: "divide",
    prefix: "divide-",
    priority: 2,
  },
  outlineWIDTH: {
    values: "number",
    group: "Borders",
    title: "Outline Width",
    className: "outline",
    prefix: "outline-",
    priority: 2,
  },
  outlineCOLOR: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Borders",
    title: "Outline Color",
    className: "outline",
    prefix: "outline-",
    priority: 2,
  },
  outlineSTYLE: {
    values: ["none", "solid", "dashed", "dotted", "double"],
    group: "Borders",
    title: "Outline Style",
    className: "outline",
    prefix: "outline-",
    priority: 2,
  },
  ringWIDTH: {
    values: "number",
    group: "Borders",
    title: "Ring Width",
    className: "ring",
    prefix: "ring-",
    priority: 2,
  },
  ringCOLOR: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Borders",
    title: "Ring Color",
    className: "ring",
    prefix: "ring-",
    priority: 2,
  },
  ringOffsetWIDTH: {
    values: "number",
    group: "Borders",
    title: "Ring Offset Width",
    className: "ring-offset",
    prefix: "ring-offset-",
    priority: 2,
  },
  ringOffsetCOLOR: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Borders",
    title: "Ring Offset Color",
    className: "ring-offset",
    prefix: "ring-offset-",
    priority: 2,
  },
  bgCOLOR: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Backgrounds",
    title: "Background Color",
    className: "bg",
    prefix: "bg-",
    priority: 2,
  },
  bgOPACITY: {
    values: "number",
    group: "Backgrounds",
    title: "Background Opacity",
    className: "bg-opacity",
    prefix: "bg-opacity-",
    priority: 2,
  },
  bgPOSITION: {
    values: [
      "bottom",
      "center",
      "left",
      "left-bottom",
      "left-top",
      "right",
      "right-bottom",
      "right-top",
      "top",
    ],
    group: "Backgrounds",
    title: "Background Position",
    className: "bg",
    prefix: "bg-",
    priority: 2,
  },
  bgSIZE: {
    values: ["auto", "cover", "contain"],
    group: "Backgrounds",
    title: "Background Size",
    className: "bg",
    prefix: "bg-",
    priority: 2,
  },
  bgREPEAT: {
    values: ["repeat", "no-repeat", "repeat-x", "repeat-y", "round", "space"],
    group: "Backgrounds",
    title: "Background Repeat",
    className: "bg",
    prefix: "bg-",
    priority: 2,
  },
  bgATTACHMENT: {
    values: ["fixed", "local", "scroll"],
    group: "Backgrounds",
    title: "Background Attachment",
    className: "bg",
    prefix: "bg-",
    priority: 2,
  },
  bgCLIP: {
    values: ["border", "padding", "content", "text"],
    group: "Backgrounds",
    title: "Background Clip",
    className: "bg-clip",
    prefix: "bg-clip-",
    priority: 2,
  },
  bgORIGIN: {
    values: ["border", "padding", "content"],
    group: "Backgrounds",
    title: "Background Origin",
    className: "bg-origin",
    prefix: "bg-origin-",
    priority: 2,
  },
  fill: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Colors",
    title: "Fill Color",
    className: "fill",
    prefix: "fill-",
    priority: 2,
  },
  strokeCOLOR: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Colors",
    title: "Stroke Color",
    className: "stroke",
    prefix: "stroke-",
    priority: 2,
  },
  strokeSIZE: {
    values: ["0", "1", "2"],
    group: "Colors",
    title: "Stroke Size",
    className: "stroke",
    prefix: "stroke-",
    priority: 2,
  },
  textOPACITY: {
    values: "number",
    group: "Colors",
    title: "Text Opacity",
    className: "text-opacity",
    prefix: "text-opacity-",
    priority: 2,
  },
  placeholderCOLOR: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Colors",
    title: "Placeholder Color",
    className: "placeholder",
    prefix: "placeholder-",
    priority: 2,
  },
  placeholderOPACITY: {
    values: "number",
    group: "Colors",
    title: "Placeholder Opacity",
    className: "placeholder-opacity",
    prefix: "placeholder-opacity-",
    priority: 2,
  },
  rotate: {
    values: ["0", "1", "2", "3", "6", "12", "45", "90", "180"],
    group: "Effects",
    title: "Rotate",
    className: "rotate",
    prefix: "rotate-",
    priority: 3,
  },
  opacity: {
    values: "number",
    group: "Effects",
    title: "Opacity",
    className: "opacity",
    prefix: "opacity-",
    priority: 3,
  },
  mixBlendMODE: {
    values: [
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten",
      "color-dodge",
      "color-burn",
      "hard-light",
      "soft-light",
      "difference",
      "exclusion",
      "hue",
      "saturation",
      "color",
      "luminosity",
    ],
    group: "Effects",
    title: "Mix Blend Mode",
    className: "mix-blend",
    prefix: "mix-blend-",
    priority: 3,
  },
  backgroundBlendMODE: {
    values: [
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten",
      "color-dodge",
      "color-burn",
      "hard-light",
      "soft-light",
      "difference",
      "exclusion",
      "hue",
      "saturation",
      "color",
      "luminosity",
    ],
    group: "Effects",
    title: "Background Blend Mode",
    className: "bg-blend",
    prefix: "bg-blend-",
    priority: 3,
  },
  shadow: {
    values: ["sm", "md", "lg", "xl", "2xl", "inner", "none"],
    group: "Effects",
    title: "Box Shadow",
    className: "shadow",
    prefix: "shadow-",
    priority: 3,
  },
  boxShadowCOLOR: {
    values: [
      "inherit",
      "current",
      "transparent",
      "black",
      "white",
      ...colorValues,
    ],
    group: "Effects",
    title: "Box Shadow Color",
    className: "shadow",
    prefix: "shadow-",
    priority: 3,
  },
  filter: {
    values: ["none"],
    group: "Effects",
    title: "Filter",
    className: "filter",
    prefix: "filter-",
    useKeyAsClass: true,
    priority: 3,
  },
  blur: {
    values: ["none", "sm", "md", "lg", "xl", "2xl", "3xl"],
    group: "Effects",
    title: "Blur",
    className: "blur",
    prefix: "blur-",
    priority: 3,
  },
  brightness: {
    values: "number",
    group: "Effects",
    title: "Brightness",
    className: "brightness",
    prefix: "brightness-",
    priority: 3,
  },
  contrast: {
    values: "number",
    group: "Effects",
    title: "Contrast",
    className: "contrast",
    prefix: "contrast-",
    priority: 3,
  },
  dropSHADOW: {
    values: ["sm", "md", "lg", "xl", "2xl", "none"],
    group: "Effects",
    title: "Drop Shadow",
    className: "drop-shadow",
    prefix: "drop-shadow-",
    priority: 3,
  },
  grayscale: {
    values: ["0", "1"],
    group: "Effects",
    title: "Grayscale",
    className: "grayscale",
    prefix: "grayscale-",
    priority: 3,
  },
  hueROTATE: {
    values: "number",
    group: "Effects",
    title: "Hue Rotate",
    className: "hue-rotate",
    prefix: "hue-rotate-",
    priority: 3,
  },
  invert: {
    values: ["0", "1"],
    group: "Effects",
    title: "Invert",
    className: "invert",
    prefix: "invert-",
    priority: 3,
  },
  saturate: {
    values: "number",
    group: "Effects",
    title: "Saturate",
    className: "saturate",
    prefix: "saturate-",
    priority: 3,
  },
  sepia: {
    values: ["0", "1"],
    group: "Effects",
    title: "Sepia",
    className: "sepia",
    prefix: "sepia-",
    priority: 3,
  },
  backdropFILTER: {
    values: ["none"],
    group: "Effects",
    title: "Backdrop Filter",
    className: "backdrop",
    prefix: "backdrop-",
    useKeyAsClass: true,
    priority: 3,
  },
  backdropBLUR: {
    values: ["none", "sm", "md", "lg", "xl", "2xl", "3xl"],
    group: "Effects",
    title: "Backdrop Blur",
    className: "backdrop-blur",
    prefix: "backdrop-blur-",
    priority: 3,
  },
  backdropBRIGHTNESS: {
    values: "number",
    group: "Effects",
    title: "Backdrop Brightness",
    className: "backdrop-brightness",
    prefix: "backdrop-brightness-",
    priority: 3,
  },
  backdropCONTRAST: {
    values: "number",
    group: "Effects",
    title: "Backdrop Contrast",
    className: "backdrop-contrast",
    prefix: "backdrop-contrast-",
    priority: 3,
  },
  backdropGRAYSCALE: {
    values: ["0", "1"],
    group: "Effects",
    title: "Backdrop Grayscale",
    className: "backdrop-grayscale",
    prefix: "backdrop-grayscale-",
    priority: 3,
  },
  backdropHueROTATE: {
    values: "number",
    group: "Effects",
    title: "Backdrop Hue Rotate",
    className: "backdrop-hue-rotate",
    prefix: "backdrop-hue-rotate-",
    priority: 3,
  },
  backdropINVERT: {
    values: ["0", "1"],
    group: "Effects",
    title: "Backdrop Invert",
    className: "backdrop-invert",
    prefix: "backdrop-invert-",
    priority: 3,
  },
  backdropOPACITY: {
    values: "number",
    group: "Effects",
    title: "Backdrop Opacity",
    className: "backdrop-opacity",
    prefix: "backdrop-opacity-",
    priority: 3,
  },
  backdropSATURATE: {
    values: "number",
    group: "Effects",
    title: "Backdrop Saturate",
    className: "backdrop-saturate",
    prefix: "backdrop-saturate-",
    priority: 3,
  },
  backdropSEPIA: {
    values: ["0", "1"],
    group: "Effects",
    title: "Backdrop Sepia",
    className: "backdrop-sepia",
    prefix: "backdrop-sepia-",
    priority: 3,
  },
  transition: {
    values: ["none", "all", "colors", "opacity", "shadow", "transform"],
    group: "Transitions",
    title: "Transition",
    className: "transition",
    prefix: "transition-",
    priority: 3,
  },
  transitionDURATION: {
    values: "number",
    group: "Transitions",
    title: "Transition Duration",
    className: "duration",
    prefix: "duration-",
    priority: 3,
  },
  transitionTimingFUNCTION: {
    values: ["linear", "in", "out", "in-out"],
    group: "Transitions",
    title: "Transition Timing Function",
    className: "ease",
    prefix: "ease-",
    priority: 3,
  },
  transitionDELAY: {
    values: "number",
    group: "Transitions",
    title: "Transition Delay",
    className: "delay",
    prefix: "delay-",
    priority: 3,
  },
  animate: {
    values: ["none", "spin", "ping", "pulse", "bounce"],
    group: "Transitions",
    title: "Animation",
    className: "animate",
    prefix: "animate-",
    priority: 3,
  },
  cursor: {
    values: [
      "auto",
      "default",
      "pointer",
      "wait",
      "text",
      "move",
      "help",
      "not-allowed",
      "none",
      "context-menu",
      "progress",
      "cell",
      "crosshair",
      "vertical-text",
      "alias",
      "copy",
      "no-drop",
      "grab",
      "grabbing",
      "all-scroll",
      "col-resize",
      "row-resize",
      "n-resize",
      "e-resize",
      "s-resize",
      "w-resize",
      "ne-resize",
      "nw-resize",
      "se-resize",
      "sw-resize",
      "ew-resize",
      "ns-resize",
      "nesw-resize",
      "nwse-resize",
      "zoom-in",
      "zoom-out",
    ],
    group: "Interactivity",
    title: "Cursor",
    className: "cursor",
    prefix: "cursor-",
    priority: 3,
  },
  pointerEVENTS: {
    values: ["none", "auto"],
    group: "Interactivity",
    title: "Pointer Events",
    className: "pointer-events",
    prefix: "pointer-events-",
    priority: 3,
  },
  resize: {
    values: ["none", "y", "x", ""],
    group: "Interactivity",
    title: "Resize",
    className: "resize",
    prefix: "resize-",
    priority: 3,
  },
  scrollBEHAVIOR: {
    values: ["auto", "smooth"],
    group: "Interactivity",
    title: "Scroll Behavior",
    className: "scroll",
    prefix: "scroll-",
    priority: 3,
  },
  scrollSNAP: {
    values: ["none", "x", "y", "both"],
    group: "Interactivity",
    title: "Scroll Snap",
    className: "snap",
    prefix: "snap-",
    priority: 3,
  },
  touchACTION: {
    values: [
      "auto",
      "none",
      "pan-x",
      "pan-left",
      "pan-right",
      "pan-y",
      "pan-up",
      "pan-down",
      "pinch-zoom",
      "manipulation",
    ],
    group: "Interactivity",
    title: "Touch Action",
    className: "touch",
    prefix: "touch-",
    priority: 3,
  },
  userSELECT: {
    values: ["none", "text", "all", "auto"],
    group: "Interactivity",
    title: "User Select",
    className: "select",
    prefix: "select-",
    priority: 3,
  },
  willCHANGE: {
    values: ["auto", "scroll", "contents", "transform"],
    group: "Interactivity",
    title: "Will Change",
    className: "will-change",
    prefix: "will-change-",
    priority: 3,
  },
};
